import React from "react";
import { useState } from "react";
import Head from "next/head";
import Header from "src/components/Organisms/header/header";
import InputSction from "src/components/Organisms/inputSction/inputSction";
import TodoListSction from "src/components/Organisms/todoListSction/todoListSction";

export default function Home() {
  const [todos, setTodos] = useState([]);

  return (
    <>
      <Head>
        <title>Todoリスト</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <InputSction todos={todos} setTodos={setTodos}/>
      <TodoListSction todos={todos} setTodos={setTodos}/>
    </>
  );
}
